[package]
name = "tokeira-types"
publish = false
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3 = "1"
serde.workspace = true
thiserror.workspace = true
time.workspace = true
uuid.workspace = true

[features]
default = []
test-support = []

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
