[package]
name = "tokeira-aws"
publish = false
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
license.workspace = true

[dependencies]
tokeira-iac = { workspace = true }
tokeira-platform = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
hex = "0.4"
sha2 = "0.10"
uuid = { version = "1", features = ["v4"] }
base64 = "0.22"
secrecy = "0.10"
http = "1"
urlencoding = "2"
shlex = "1"
which = "7"

# AWS SDK
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-sdk-ec2 = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-eks = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-ecs = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-iam = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-ecr = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-autoscaling = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-ssm = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-s3 = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio", "sigv4a", "http-1x"] }
aws-sdk-dsql = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-dynamodb = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-elasticloadbalancingv2 = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-secretsmanager = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-servicediscovery = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-sts = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio", "sigv4a"] }
aws-iam = "0.2.2"

[dev-dependencies]
proptest = "1"

[lints]
workspace = true
