[package]
name = "tokeirad"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
time.workspace = true
tokio.workspace = true
tonic.workspace = true
tonic-reflection.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokeira-edge = { path = "../../crates/tokeira-edge" }
tokeira-kernel = { path = "../../crates/tokeira-kernel" }
tokeira-proto = { path = "../../crates/tokeira-proto" }
tokeira-projection = { path = "../../crates/tokeira-projection" }
tokeira-runtime = { path = "../../crates/tokeira-runtime" }
tokeira-storage = { path = "../../crates/tokeira-storage" }
tokeira-types = { path = "../../crates/tokeira-types" }

[dev-dependencies]
tokio-stream = { version = "0.1", features = ["net"] }
