//! Execution of an assembled program through Monty, with error translation.
//!
//! Monty only ever sees the transient generated program, so every position it
//! reports — parse errors and runtime tracebacks alike — is in generated
//! coordinates. This module owns the translation back: generated (line, col)
//! → generated byte offset → source-map segment → original offset → original
//! (line, col). Operators see `.tkdp` positions or an explicit internal-region
//! label; raw generated coordinates never escape.
//!
//! Monty reports 1-based lines and 1-based *character* columns, so both
//! directions of the translation convert through character counts rather than
//! assuming ASCII.

use monty::MontyRun;
use monty_types::{CompileOptions, MontyException, MontyObject, PrintWriter, ResourceTracker};
use ruff_text_size::TextSize;

use crate::{
    program::Program,
    source_map::{LineTable, Mapped, SourceMap},
};

/// A successful run.
#[derive(Debug)]
pub struct RunOutcome {
    /// Python repr of the module result (the driver's final expression).
    pub value: String,
    /// Captured `print` output, stdout and stderr interleaved in emit order.
    pub output: String,
}

/// A failed run, already rendered in operator terms.
#[derive(Debug, thiserror::Error)]
#[error("{rendered}")]
pub struct RunFailure {
    pub rendered: String,
}

/// Compiles and runs the program, translating any failure through the map.
pub fn execute(
    program: &Program,
    file_label: &str,
    original: &str,
) -> Result<RunOutcome, RunFailure> {
    let translator = Translator {
        map: &program.map,
        generated: LineTable::new(&program.text),
        generated_text: &program.text,
        original_table: LineTable::new(original),
        original,
        file_label,
    };

    let runner = MontyRun::new(
        program.text.clone(),
        file_label,
        Vec::new(),
        CompileOptions::default(),
    )
    .map_err(|exc| translator.render_failure(&exc, "definition rejected"))?;

    let mut output = String::new();
    let result = runner.run(
        Vec::new(),
        ResourceTracker::default(),
        PrintWriter::CollectString(&mut output, Some(1 << 20)),
    );
    match result {
        Ok(value) => Ok(RunOutcome {
            value: render_value(&value),
            output,
        }),
        Err(exc) => Err(translator.render_failure(&exc, "definition failed")),
    }
}

fn render_value(value: &MontyObject) -> String {
    value.py_repr()
}

struct Translator<'a> {
    map: &'a SourceMap,
    generated: LineTable,
    generated_text: &'a str,
    original_table: LineTable,
    original: &'a str,
    file_label: &'a str,
}

impl Translator<'_> {
    fn render_failure(&self, exc: &MontyException, verdict: &str) -> RunFailure {
        let mut rendered = format!("error: {verdict}: {}\n", exception_summary(exc));
        for frame in exc.traceback() {
            rendered.push_str(&self.render_frame(frame.start.line, frame.start.column));
        }
        if exc.traceback().is_empty() {
            rendered.push_str("  (no traceback reported by monty)\n");
        }
        RunFailure { rendered }
    }

    fn render_frame(&self, line: u32, column: u32) -> String {
        let offset = self.generated_offset(line, column);
        match self.map.translate(offset) {
            Some(Mapped::Original { offset, context }) => {
                let (oline, ocol) = self.original_position(offset);
                let mut s = format!("  at {}:{oline}:{ocol}", self.file_label);
                if let Some(kind) = context {
                    s.push_str(&format!(" ({})", kind.describe()));
                }
                s.push('\n');
                if let Some(text) = self.original_line_text(oline) {
                    s.push_str(&format!("    {}\n", text.trim_end()));
                }
                s
            }
            Some(Mapped::Prelude) => "  in the tokeira prelude (internal)\n".to_owned(),
            Some(Mapped::Driver) => "  in the tokeira driver (internal)\n".to_owned(),
            None => format!("  at <generated>:{line}:{column} (unmapped)\n"),
        }
    }

    /// Generated (1-based line, 1-based char column) → byte offset.
    fn generated_offset(&self, line: u32, column: u32) -> TextSize {
        let line_start = self.generated.line_start(line);
        let line_text = &self.generated_text[usize::from(line_start)..];
        let line_text = line_text.split('\n').next().unwrap_or("");
        let byte_col = char_to_byte_col(line_text, column);
        line_start + TextSize::new(byte_col)
    }

    /// Original byte offset → (1-based line, 1-based char column).
    fn original_position(&self, offset: TextSize) -> (u32, u32) {
        let (line, byte_col) = self.original_table.line_column(offset);
        let line_start = self.original_table.line_start(line);
        let line_text = &self.original[usize::from(line_start)..];
        let char_col = line_text[..(byte_col - 1) as usize].chars().count() as u32 + 1;
        (line, char_col)
    }

    fn original_line_text(&self, line: u32) -> Option<&str> {
        let start = usize::from(self.original_table.line_start(line));
        self.original[start..].split('\n').next()
    }
}

/// Byte column (0-based) for a 1-based character column within a line.
fn char_to_byte_col(line: &str, char_col: u32) -> u32 {
    let want = char_col.saturating_sub(1) as usize;
    line.char_indices()
        .nth(want)
        .map_or(line.len() as u32, |(i, _)| i as u32)
}

/// `ExcType: message` with monty's own type spelling, no trailing period.
fn exception_summary(exc: &MontyException) -> String {
    match exc.message() {
        Some(msg) => format!("{}: {msg}", exc.exc_type()),
        None => exc.exc_type().to_string(),
    }
}
