[package]
name = "tkp"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokeira-provisioner = { workspace = true }
tokeira-state = { workspace = true }
tokeira-build-info = { workspace = true }
tokeira-config = { workspace = true }
tokeira-iac = { path = "../../crates/tokeira-iac" }
tokeira-orchestrator = { path = "../../crates/tokeira-orchestrator" }
tokeira-local-deployment = { path = "../../platforms/local" }

[dev-dependencies]
tempfile.workspace = true
