//! Lexical tokens for the platform DSL.
//!
//! The lexer is generated by [`logos`]; this module owns the only token
//! definition for the language. It sits at the front of the compile pipeline
//! (lex → parse → resolve → type-check → lower) described in the
//! `platform-config-dsl` design, and produces `(Token, Span)` pairs the parser
//! consumes. Lexing performs no I/O and is total — a guarantee the whole
//! compiler depends on (Property 1).

use logos::Logos;

/// A byte-offset source range, used for every diagnostic and AST node.
///
/// Half-open `[start, end)` into the original source string. `logos` produces
/// these directly via `Lexer::span`, and they flow unchanged through the parser
/// so an error can always point at the exact source text (Requirement 6.1).
pub type Span = core::ops::Range<usize>;

/// The complete token set of the platform DSL.
///
/// Keywords are distinct variants (not `Ident`) so the parser never has to
/// re-classify an identifier. Whitespace and `//` line comments are skipped by
/// the lexer and never reach the parser. Longest-match resolves the operator
/// overlaps that matter: `++` over a hypothetical `+`, `..` over `.`, and `=>`
/// over `=` — `logos` picks the longest token, so order here is irrelevant.
#[derive(Logos, Debug, Clone, PartialEq)]
#[logos(skip r"[ \t\r\n\f]+")]
#[logos(skip r"//[^\n]*")]
pub enum Token {
    // ── Keywords ──────────────────────────────────────────────────────
    /// `platform` — opens the single platform declaration.
    #[token("platform")]
    Platform,
    /// `use` — a relative, downward-only import of another `.platform` file
    /// (import containment is enforced during assembly, Requirement 13).
    #[token("use")]
    Use,
    /// `input` — an operator-tunable configuration value.
    #[token("input")]
    Input,
    /// `let` — a local binding (pure, evaluated against inputs/`ctx`).
    #[token("let")]
    Let,
    /// `module` — groups resources/services and carries ownership.
    #[token("module")]
    Module,
    /// `when` — conditional presence of a module/declaration on a typed cond.
    #[token("when")]
    When,
    /// `match` — typed-sum dispatch (e.g. on `storage` / `dsql` mode).
    #[token("match")]
    Match,
    /// `is` — sugar in `when <field> is <Variant>`.
    #[token("is")]
    Is,
    /// `namespaces` — the tenancy units the deployment requires.
    #[token("namespaces")]
    Namespaces,
    /// `writeback` — declarative state→config writeback targets.
    #[token("writeback")]
    Writeback,
    /// `service` — a service-kind instantiation.
    #[token("service")]
    Service,
    /// `resource` — a resource-kind instantiation.
    #[token("resource")]
    Resource,
    /// `image` — an image-kind declaration (Build/Mirror).
    #[token("image")]
    Image,
    /// `depends_on` — explicit dependency edges (module- or item-level).
    #[token("depends_on")]
    DependsOn,
    /// `true` literal.
    #[token("true")]
    True,
    /// `false` literal.
    #[token("false")]
    False,

    // ── Punctuation / operators ───────────────────────────────────────
    #[token("{")]
    LBrace,
    #[token("}")]
    RBrace,
    #[token("[")]
    LBracket,
    #[token("]")]
    RBracket,
    #[token("(")]
    LParen,
    #[token(")")]
    RParen,
    #[token(":")]
    Colon,
    #[token(",")]
    Comma,
    /// `=>` — match-arm separator.
    #[token("=>")]
    FatArrow,
    /// `=` — declaration binding.
    #[token("=")]
    Eq,
    /// `++` — list concatenation (lists only; record merge is `..` spread).
    #[token("++")]
    PlusPlus,
    /// `..` — record spread (`{ ..base, key: v }`).
    #[token("..")]
    DotDot,
    /// `.` — field/output access (e.g. `dsql.cluster.cluster_arn`).
    #[token(".")]
    Dot,
    /// `/` — path join over `Path` values.
    #[token("/")]
    Slash,

    // ── Literals and identifiers ──────────────────────────────────────
    /// An identifier: a name reference, declaration name, kind name, or field
    /// key. Resolution into bindings/kinds happens in later phases, not here.
    #[regex(r"[A-Za-z_][A-Za-z0-9_]*", |lex| lex.slice().to_string())]
    Ident(String),
    /// A non-negative integer literal.
    #[regex(r"[0-9]+", |lex| lex.slice().parse::<i64>().ok())]
    Int(i64),
    /// A double-quoted string literal, with surrounding quotes stripped.
    ///
    /// Escape sequences are accepted by the regex but not yet unescaped; the
    /// parser phase owns unescaping so a malformed escape becomes a located
    /// diagnostic rather than a silent lex failure.
    #[regex(r#""([^"\\]|\\.)*""#, |lex| { let s = lex.slice(); s[1..s.len() - 1].to_string() })]
    Str(String),
}
