[package]
name = "tokeira-kinds"
publish = false
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde_json.workspace = true
tokeira-aws = { path = "../tokeira-aws" }
tokeira-compose = { path = "../tokeira-compose" }
tokeira-iac = { path = "../tokeira-iac" }
tokeira-platform = { path = "../tokeira-platform" }

[lints]
workspace = true
