[package]
name = "hello-workflow"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
publish = false

[workspace]

[dependencies]
anyhow = "1"
futures = "0.3"
tokeira-engine = "0.2.0"
temporalio-client = "1.0"
temporalio-common = "1.0"
temporalio-macros = "1.0"
temporalio-sdk = "1.0"
temporalio-workflow = "1.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
url = "2"

