[package]
name = "tokeira-chasm-derive"
description = "Derive macro for Tokeira durable state-machine components"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["tokeira", "derive", "state-machine"]
categories = ["development-tools::procedural-macro-helpers"]
publish = true

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

[lints]
workspace = true
