[package]
name = "tokeira-kernel"
publish = false
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
smallvec.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
tokeira-types = { path = "../tokeira-types" }

[dev-dependencies]
postcard = { version = "1.0", features = ["alloc"] }
prost = "0.12"
proptest = "1.6"
tokeira-proto = { path = "../tokeira-proto" }
tokeira-types = { path = "../tokeira-types", features = ["test-support"] }

[lints]
workspace = true
