[package]
name = "tokeira-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
smallvec.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
tokeira-types = { path = "../tokeira-types" }

[dev-dependencies]
prost = "0.12"
proptest = "1.6"
tokeira-proto = { path = "../tokeira-proto" }
