[package]
name = "tokeira-compose"
publish = false
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
askama = "0.12"
async-trait.workspace = true
bollard.workspace = true
futures-util = "0.3"
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
sha2.workspace = true
tracing.workspace = true
thiserror.workspace = true
tokeira-deploy-engine = { path = "../tokeira-deploy-engine" }
tokeira-iac = { path = "../tokeira-iac" }
tokeira-platform = { path = "../tokeira-platform" }

[dev-dependencies]
proptest = "1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
