[package]
name = "tokeira-controller"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
prost-types = "0.12"
serde.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
tonic.workspace = true
uuid.workspace = true
tokeira-proto = { path = "../tokeira-proto" }
tokeira-storage = { path = "../tokeira-storage" }
tokeira-types = { path = "../tokeira-types" }

[dev-dependencies]
proptest = "1"
