[package]
name = "tokeira-storage"
publish = false
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-channel = { version = "2.3", optional = true }
async-trait.workspace = true
aurora-dsql-sqlx-connector = { version = "=0.1.2", features = ["pool"], optional = true }
aws-config = { version = "1", features = ["behavior-version-latest"], optional = true }
aws-sdk-dynamodb = { version = "1", optional = true }
aws-smithy-runtime-api = { version = "1", features = ["client"], optional = true }
metrics.workspace = true
postcard = { version = "1.0", features = ["alloc"], optional = true }
rand = { version = "0.8", optional = true }
serde.workspace = true
sha2.workspace = true
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio", "tls-rustls", "postgres", "time", "uuid"], optional = true }
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tokeira-kernel = { path = "../tokeira-kernel" }
tokeira-observability = { path = "../tokeira-observability" }
tokeira-types = { path = "../tokeira-types" }
tokeira-chasm = { path = "../tokeira-chasm" }
uuid.workspace = true

[features]
default = []
dsql = [
    "dep:async-channel",
    "dep:aurora-dsql-sqlx-connector",
    "dep:aws-config",
    "dep:aws-sdk-dynamodb",
    "dep:aws-smithy-runtime-api",
    "dep:postcard",
    "dep:rand",
    "dep:sqlx",
]
dsql-integration = ["dsql"]

[build-dependencies]
sha2.workspace = true

[dev-dependencies]
metrics-util.workspace = true
proptest = "1"
toml.workspace = true
tokeira-types = { path = "../tokeira-types", features = ["test-support"] }
tracing-subscriber.workspace = true
uuid.workspace = true

[lints]
workspace = true
