[package]
name = "tokeira-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
metrics.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
tokeira-kernel = { path = "../tokeira-kernel" }
tokeira-types = { path = "../tokeira-types" }

[dev-dependencies]
metrics-util.workspace = true
proptest = "1"
tracing-subscriber.workspace = true
