//! The component model and lifecycle.
//!
//! A CHASM **Component** is the unit of durable state and behaviour. Every
//! component reports a [`LifecycleState`] (`Running`/`Completed`/`Failed`) computed
//! from its own state, and a **root** component's closure drives closure of the
//! whole Execution (Requirement 2.1–2.4). A component declares its persistent
//! children as typed [`field`](crate::field) members and carries exactly one data
//! field (Requirement 2.5, 2.6); the static [`FieldRegistry`] that makes this
//! walkable is generated at compile time by `tokeira-chasm-derive`, never by
//! runtime reflection (Requirement 3.1).
//!
//! ## Why the trait is split into [`Component`] + [`Lifecycle`]
//!
//! The design names a single `Component` trait with `Data`/`FQN`/`fields()` *and*
//! `lifecycle_state()`. A `#[derive(Component)]` macro can generate the first
//! three (they are mechanical: the data type, the name attribute, and the static
//! field registry), but it **cannot** generate `lifecycle_state` — that is the one
//! piece of genuine per-component behaviour the author must write. A derive macro
//! also cannot emit a *partial* trait impl. So the contract is split into two
//! traits with an explicit bound rather than a fragile "implement this method by
//! convention" scheme:
//!
//! - [`Lifecycle`] — the author writes `lifecycle_state` here, by hand.
//! - [`Component`] — `#[derive(Component)]` generates the whole impl; its
//!   `lifecycle_state` delegates to `<Self as Lifecycle>`, so a component that
//!   forgets to implement [`Lifecycle`] fails to compile.
//!
//! This keeps "implementors hand-write only `lifecycle_state`" true (the design's
//! intent) while staying within what a derive macro can soundly produce, and it
//! makes the requirement a real trait bound (a clear compile error) rather than a
//! naming convention. This is a deliberate, documented deviation from the design's
//! single-trait sketch (`AGENTS §9`: state deliberate deviations explicitly).
//!
//! Lifecycle is **derived, not stored**: [`LifecycleState::is_closed`] is true
//! exactly for `Completed`/`Failed`, and a closing root closes the Execution
//! (enforced by the engine, Requirement 2.3, 2.4). Component code never panics for
//! framework errors — it returns [`ChasmError`](crate::ChasmError).

use serde::{Deserialize, Serialize};

use crate::{context::Context, error::ChasmError, field::FieldRegistry};

/// The lifecycle of a component, computed from its own state. Mirrors
/// `chasm/component.go:16,40 @ v1.31.0`, where the state is a bitmask and
/// `IsClosed = state >= Completed`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum LifecycleState {
    /// The component is live and may still transition.
    Running,
    /// The component reached a successful terminal state.
    Completed,
    /// The component reached an unsuccessful terminal state (failed, canceled,
    /// terminated, or timed out — all map here at the lifecycle level).
    Failed,
}

impl LifecycleState {
    /// True iff the component has reached a terminal state (`Completed`/`Failed`),
    /// matching upstream's `state >= Completed` (`component.go:40 @ v1.31.0`). A
    /// closing **root** closes the whole Execution (Requirement 2.3).
    pub fn is_closed(self) -> bool {
        matches!(self, LifecycleState::Completed | LifecycleState::Failed)
    }
}

/// The author-written half of the component contract: how a component computes its
/// [`LifecycleState`] from its own state.
///
/// This is the *only* method a component author hand-writes; everything else on
/// [`Component`] is generated by `#[derive(Component)]`. See the module doc for why
/// the contract is split this way. The method takes a read-only [`Context`] because
/// a component's lifecycle may depend on the state of child components reached
/// through the tree.
pub trait Lifecycle {
    /// The component's current lifecycle, derived from its own (and possibly its
    /// children's) state. Must be a pure function of state — no I/O, no mutation.
    fn lifecycle_state(&self, ctx: &dyn Context) -> LifecycleState;
}

/// A unit of durable state and behaviour.
///
/// Implemented via `#[derive(Component)]`, which generates [`fields`](Component::fields)
/// from the struct's declared [`Field`](crate::field::Field)/[`Map`](crate::field::Map)/
/// [`ParentPtr`](crate::field::ParentPtr) members (replacing Go's reflection-based
/// iteration — design HP1), fixes [`Data`](Component::Data) to the `#[chasm(data)]`
/// field's payload type, and reads [`FQN`](Component::FQN) from the
/// `#[chasm(fqn = "...")]` attribute. The generated `lifecycle_state` delegates to
/// the author's [`Lifecycle`] impl.
pub trait Component: Lifecycle + Sized + 'static {
    /// The data field's proto payload type. A component has **exactly one** data
    /// field; the derive macro enforces this at compile time (Requirement 2.6,
    /// 3.2).
    type Data: prost::Message + Default;

    /// The component's stable fully-qualified name, e.g. `"activity.activity"`.
    /// Used for archetype/type-id indexing in the [`registry`](crate::registry)
    /// (Requirement 8.1).
    const FQN: &'static str;

    /// The component's static field registry, used by the node tree to walk and
    /// persist its children (Requirement 2.5, 3.1). Generated by the derive macro.
    fn fields(&self) -> FieldRegistry<'_>;
}

/// Read-only metadata carried alongside a root component (Requirement 2.9).
///
/// Mirrors upstream `ContextMetadata` (`chasm/context.go @ v1.31.0`) in spirit: the
/// request-scoped provenance the engine threads through a transition. Kept minimal
/// here (the originating request id); additional fields are appended as archetypes
/// need them, never inserted mid-order (so existing positional/serde shape is
/// stable).
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct ContextMetadata {
    /// The id of the request that created or last drove the execution, if known.
    pub request_id: Option<String>,
}

/// Why a root component is being terminated (Requirement 2.9).
///
/// Carries the operator-supplied `reason` and the `identity` of the terminator,
/// mirroring the termination provenance Temporal records. `details` is left to the
/// archetype (it is opaque payload bytes at this layer); it is `None` when no
/// details were supplied.
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct TerminateReason {
    /// Human-readable reason for the termination.
    pub reason: String,
    /// Identity of the actor requesting termination, if supplied.
    pub identity: Option<String>,
    /// Optional opaque details payload, interpreted by the archetype.
    pub details: Option<Vec<u8>>,
}

/// A root component: the top of an execution's node tree.
///
/// Beyond [`Component`], a root additionally supports termination and carries
/// [`ContextMetadata`]. When a root's [`lifecycle_state`](Lifecycle::lifecycle_state)
/// becomes closed, the engine closes the whole Execution (Requirement 2.3); a
/// non-root component closing does not.
pub trait RootComponent: Component {
    /// Terminate the root, transitioning it to a closed lifecycle. Runs inside a
    /// transition (hence `&mut dyn MutableContext`); returns [`ChasmError`] on an
    /// illegal termination rather than panicking.
    fn terminate(
        &mut self,
        ctx: &mut dyn crate::context::MutableContext,
        reason: &TerminateReason,
    ) -> Result<(), ChasmError>;

    /// The execution's context metadata.
    fn context_metadata(&self) -> &ContextMetadata;
}

/// Bridges a [`Component`] to and from its root data node so an engine can
/// materialize it.
///
/// MVP materialization reconstructs a component from its single `#[chasm(data)]`
/// field: `from_data` wraps the persisted proto, `into_data` extracts it. This is a
/// **pure** component ↔ data contract with no engine dependency, so a component
/// crate (e.g. `tokeira-chasm-activity`) implements it without depending on the
/// runtime (Requirement 1.4). The runtime's typed engine uses it at the node
/// boundary; richer multi-node materialization, when needed, supersedes it.
pub trait EngineComponent: Component {
    /// Reconstruct the component from its persisted root data.
    fn from_data(data: Self::Data) -> Self;

    /// Extract the component's root data for persistence.
    fn into_data(self) -> Self::Data;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lifecycle_closed_only_for_terminal_states() {
        assert!(!LifecycleState::Running.is_closed());
        assert!(LifecycleState::Completed.is_closed());
        assert!(LifecycleState::Failed.is_closed());
    }

    #[test]
    fn lifecycle_state_round_trips() {
        for state in [
            LifecycleState::Running,
            LifecycleState::Completed,
            LifecycleState::Failed,
        ] {
            let json = serde_json::to_string(&state).expect("serialize");
            let back: LifecycleState = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(state, back);
        }
    }

    #[test]
    fn terminate_reason_and_metadata_round_trip() {
        let metadata = ContextMetadata {
            request_id: Some("req-1".to_owned()),
        };
        let reason = TerminateReason {
            reason: "operator request".to_owned(),
            identity: Some("op@example".to_owned()),
            details: Some(vec![0xAB, 0xCD]),
        };
        for (label, json) in [
            ("metadata", serde_json::to_string(&metadata).expect("ser")),
            ("reason", serde_json::to_string(&reason).expect("ser")),
        ] {
            assert!(!json.is_empty(), "{label} serializes");
        }
        let back_meta: ContextMetadata =
            serde_json::from_str(&serde_json::to_string(&metadata).unwrap()).unwrap();
        let back_reason: TerminateReason =
            serde_json::from_str(&serde_json::to_string(&reason).unwrap()).unwrap();
        assert_eq!(metadata, back_meta);
        assert_eq!(reason, back_reason);
    }
}
