[package]
name = "tokeira-autoscaler"
publish = false
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
buffa = { version = "0.6", features = ["json"] }
connectrpc = { version = "0.6", features = ["client"] }
metrics.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokeira-config.workspace = true
tokeira-observability = { path = "../tokeira-observability" }
tokeira-proto = { path = "../tokeira-proto" }
tokeira-storage = { path = "../tokeira-storage" }
tokeira-types = { path = "../tokeira-types" }
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true

[dev-dependencies]
metrics-util.workspace = true
proptest.workspace = true

[lints]
workspace = true
