[package]
name = "tokeira-tkdp"
publish = false
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[package.metadata.tokeira.definition-frontend]
format = "tkdp"
source-extension = "tkdp"
default-relative-path = "definition.tkdp"

[dependencies]
monty.workspace = true
monty-types.workspace = true
ruff_python_ast.workspace = true
ruff_python_parser.workspace = true
ruff_text_size.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokeira-orchestrator = { path = "../tokeira-orchestrator" }
tokeira-platform = { path = "../tokeira-platform" }

[dev-dependencies]
proptest = "1"
tokeira-iac = { path = "../tokeira-iac" }

[lints]
workspace = true
