format_version = 1
tokeira_release = "0.5.1"
minimum_supported_version = 1
target_version = 81
maximum_readable_version = 81
migration_set_digest = "sha256:5db3e7e9e528b742ba7f6ee35aa4cec67b42706be3688ff6b527130c544f1df1"
immutable_through_version = 81
