[package]
name = "tokeira-proto"
publish = false
version = "0.1.0"
edition = "2024"
rust-version.workspace = true
description = "Temporal-compatible and Tokeira-internal protobuf bindings"
license = "Apache-2.0"

[dependencies]
buffa = { version = "0.6", features = ["json"] }
buffa-types = { version = "0.6", features = ["json"] }
connectrpc = { version = "0.6", features = ["client"] }
http-body = "1"
prost = "0.12"
prost-types = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
time = { version = "0.3", features = ["serde", "formatting", "parsing"] }
tonic = { version = "0.11", features = ["transport"] }
uuid = { version = "1", features = ["serde", "v4"] }

[dependencies.tokeira-types]
path = "../tokeira-types"

[build-dependencies]
connectrpc-build = "0.6"
tonic-build = "0.11"
walkdir = "2"

[dev-dependencies]
serde_yaml.workspace = true

[lints]
workspace = true
