[package]
name = "tokeira-edge"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
async-trait = "0.1"
http = "1"
prost = "0.12"
prost-types = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
time = { version = "0.3", features = ["formatting", "parsing", "serde"] }
tokio = { version = "1", features = ["sync", "time", "macros", "rt", "test-util"] }
tokio-util = { version = "0.7", features = ["rt"] }
tonic.workspace = true
tracing = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }

[dependencies.tokeira-kernel]
path = "../tokeira-kernel"

[dependencies.tokeira-proto]
path = "../tokeira-proto"

[dependencies.tokeira-runtime]
path = "../tokeira-runtime"

[dependencies.tokeira-storage]
path = "../tokeira-storage"

[dependencies.tokeira-types]
path = "../tokeira-types"

[dev-dependencies]
proptest = "1"
